### ISSUE TITLE
Philosophy: file and folder layout

### ISSUE THREAD

**Issue by BBI-YggyKing** [Mervill/UnityLitJson#2]
_Should we preserve the original file and folder naming conventions or overhaul as we see fit?_

The benefit of keeping the old names is that merging from disparate sources will be simplified. Git's content-based tracking helps here, but if someone has simply copied a bunch of files and made changes, git won't be able to help.

The benefit of overhauling is to set up a logical layout that makes sense for all concerned and encompasses the Unity integration in a logical fashion. If we are going to make changes, now is the time.

**Comment by BBI-YggyKing** [comment]
I'm inclined to keep the current file and folder naming and layout, and just add additional folder(s) as needed for Unity support. But I could easily be swayed either way.

**Comment by Mervill** [comment]
No that seems like the best way to do things. Really all we need to do to 'support' Unity is build a .unitypackage with the source code in it at each significant release.

**Comment by BBI-YggyKing** [comment]
"with the source code" or with a DLL ... both options could easily be made available and people can choose which they prefer.

Vaguely related, were you thinking of putting this on the Asset Store as a free package, or just use github for distribution?

**Comment by Mervill** [comment]
We can infrequently push to a store page, but it should direct people to the repository if they want the latest copy.

**Comment by BBI-YggyKing** [comment]
Which brings up the more general question of support. For me, I'm willing to invest a little bit extra in the package in order to create a shared resource for the Unity community, but I can't afford hours every week on supporting it. I'm guessing you feel the same. So anything we can do to minimize administrative overhead makes sense -- plus doing a decent job on docs and unit tests in the first release.

**Comment by Mervill** [comment]
As I mentioned in another Issue, I can take ownership of Unity compatibility since I'll probably be contributing less to the core library.
